disp('LCR-1')
vis_circles('circles','aem',95)
vis_circles('circles','50',90)
vis_circles('circles','5',93)
vis_circles('circles','1',92)
vis_circles('circles','05',88)

disp('LCR-10')
vis_circles('circles_10','aem',99)
vis_circles('circles_10','50',91)
vis_circles('circles_10','5',92)
vis_circles('circles_10','1',92)
vis_circles('circles_10','05',93)

disp('LCR-0.2')
vis_circles('circles_d5','aem',86)
vis_circles('circles_d5','50',98)
vis_circles('circles_d5','5',97)
vis_circles('circles_d5','1',91)
vis_circles('circles_d5','05',93)

disp('Airplane')
vis_iter('airplane','airplane','aem',109)
vis_iter('airplane','airplane','50',91)
vis_iter('airplane','airplane','5',88)
vis_iter('airplane','airplane','1',91)
vis_iter('airplane','airplane','05',91)

disp('DR')
vis_iter('panoramica','Panoramica','aem',27)
vis_iter('panoramica','Panoramica','50',27)
vis_iter('panoramica','Panoramica','5',27)
vis_iter('panoramica','Panoramica','1',24)
vis_iter('panoramica','Panoramica','05',24)
%close all;
%exit;
